const puppet = require('puppeteer');
const fs = require('fs');
const _ = require('lodash')

const links = [
    'www.mit.edu',
    'www.stanford.edu',
    'www.berkeley.edu',
    'www.uiuc.edu',
    'www.umich.edu',
    'www.cornell.edu',
    'www.utexas.edu',
    'www.umd.edu',
    'www.ucsd.edu',
    'www.caltech.edu',
    'www.wisc.edu',
    'www.ucla.edu',
    'www.harvard.edu',
    'www.cmu.edu',
    'www.purdue.edu',
    'www.princeton.edu',
    'www.psu.edu',
    'www.gatech.edu',
    'www.vt.edu',
    'www.tamu.edu',
    'www.duke.edu',
    'www.washington.edu',
    'www.umn.edu',
    'www.columbia.edu',
    'www.yale.edu',
    'www.osu.edu',
    'www.pitt.edu',
    'www.brown.edu',
    'www.jhu.edu',
    'www.ncsu.edu',
    'www.dartmouth.edu',
    'www.iastate.edu',
    'www.ucsb.edu',
    'www.cwru.edu',
    'www.northwestern.edu',
    'www.asu.edu',
    'www.uiowa.edu',
    'www.rutgers.edu',
    'www.rice.edu',
    'www.rochester.edu',
    'www.virginia.edu',
    'www.upenn.edu',
    'www.udel.edu',
    'www.ucdavis.edu',
    'www.colorado.edu',
    'www.nd.edu',
    'www.uchicago.edu',
    'www.lehigh.edu',
    'www.usc.edu',
    'www.rpi.edu',
    'www.uc.edu',
    'www.ufl.edu',
    'www.wustl.edu',
    'www.vanderbilt.edu',
    'www.uci.edu',
    'www.msu.edu',
    'www.umass.edu',
    'www.ksu.edu',
    'www.ua.edu',
    'www.uarizona.edu',
    'www.unc.edu',
    'www.mines.edu',
    'www.uic.edu',
    'www.unh.edu',
    'www.unm.edu',
    'www.bu.edu',
    'www.colostate.edu',
    'www.auburn.edu',
    'www.buffalo.edu',
    'www.uakron.edu',
    'www.drexel.edu',
    'www.syr.edu',
    'www.oregonstate.edu',
    'www.clemson.edu',
    'www.umr.edu',
    'www.unl.edu',
    'www.uconn.edu',
    'www.utah.edu',
    'www.utk.edu',
    'www.wvu.edu',
    'www.ku.edu',
    'www.sunnysb.edu',
    'www.uga.edu',
    'www.mizzou.edu',
    'www.okstate.edu',
    'www.lsu.edu',
    'www.sc.edu',
    'www.tulane.edu',
    'www.indiana.edu',
    'www.ou.edu',
    'www.miami.edu',
    'www.utdallas.edu',
    'www.ohiou.edu',
    'www.uh.edu',
    'www.mtu.edu',
    'www.umaine.edu',
    'www.uky.edu',
    'www.gwu.edu',
    'www.ucf.edu',
    'www.niu.edu',
    'www.iupui.edu',
    'www.memphis.edu',
    'www.unlv.edu',
    'www.uah.edu',
    'www.uidaho.edu',
    'www.msstate.edu',
    'www.umkc.edu',
    'www.uncc.edu',
    'www.ogi.edu',
    'www.gmu.edu',
    'www.uindy.edu',
    'www.unomaha.edu',
    'www.usf.edu',
    'www.mtsu.edu',
    'www.poly.edu',
    'www.uno.edu',
    'www.uark.edu',
    'www.tntech.edu',
    'www.usf.edu',
    'www.lousiana.edu',
    'www.fit.edu',
    'www.iit.edu',
    'www.wsu.edu',
    'www.gsu.edu',
    'www.ttu.edu',
    'www.wayne.edu',
    'www.csus.edu',
    'www.missouristate.edu',
    'www.nmsu.edu',
    'www.ndsu.edu',
    'www.uta.edu',
    'www.clarkson.edu',
    'www.wright.edu',
    'www.utc.edu',
    'www.utulsa.edu',
    'www.pdx.edu',
    'www.uvm.edu',
    'www.baylor.edu',
    'www.villanova.edu',
    'www.utampa.edu',
    'www.latech.edu',
    'www.njit.edu',
    'www.isu.edu',
    'www.wichita.edu',
    'www.olemiss.edu',
    'www.northeastern.edu',
    'www.siue.edu',
    'www.uaf.edu',
    'www.pace.edu',
    'www.wright.edu',
    'www.csu.edu',
    'www.sdsu.edu',
    'www.ecu.edu',
    'www.unt.edu',
    'www.sunyit.edu',
    'www.umsl.edu',
    'www.uni.edu',
    'www.utoledo.edu',
    'www.uis.edu',
    'www.odu.edu',
    'www.nwmissouri.edu',
    'www.lamar.edu',
    'www.ilstu.edu',
    'www.louisville.edu',
    'tamu-commerce.edu',
    'www.coloradotech.edu',
    'www.boisestate.edu',
    'www.montana.edu',
    'www.sdsmt.edu',
    'www.ncat.edu',
    'www.siuc.edu',
    'www.fiu.edu',
    'www.nodak.edu',
    'www.wku.edu',
    'www.bradley.edu',
    'www.csuohio.edu',
    'www.bridgeport.edu',
    'www.udayton.edu',
    'www.tamuk.edu',
    'www.uwf.edu',
    'www.emich.edu',
    'www.mnsu.edu',
    'www.suffolk.edu',
    'www.uncg.edu',
    'www.nmt.edu',
    'www.uca.edu',
    'www.seu.edu',
    'www.hawai.edu',
    'www.uttyler.edu',
    'www.ewu.edu',
    'www.sou.edu',
    'www.utsa.edu',
    'www.westga.edu',
    'www.bsu.edu',
    'www.utep.edu',
    'www.colstate.edu',
    'www.astate.edu',
    'www.du.edu',
    'www.ndsu.edu',
    'www.nyit.edu',
    'www.csuchico.edu',
    'www.dsu.edu',
    'www.stcloudstate.edu',
    'www.marquette.edu',
    'www.temple.edu',
    'www.cuny.edu',
    'www.neiu.edu',
    'www.udmercy.edu',
    'www.ualr.edu',
    'www.csufresno.edu',
    'www.aamu.edu',
    'www.widener.edu',
    'www.alcorn.edu',
    'www.gannon.edu',
    'www.findlay.edu',
    'www.sdsu.edu',
    'www.bsu.edu',
    'www.npu.edu',
    'www.jsu.edu',
    'www.sju.edu',
    'www.chapman.edu',
    'www.kent.edu',
    'www.ferris.edu',
    'www.newhaven.edu',
    'www.fdu.edu',
    'www.albany.edu',
    'www.wm.edu',
    'www.etsu.edu',
    'www.swt.edu',
    'www.mcneese.edu',
    'www.oakland.edu',
    'www.sjsu.edu',
    'www.wpunj.edu',
    'www.wcu.edu',
    'www.ucok.edu',
    'www.widener.edu',
    'www.stthomas.edu',
    'www.wiu.edu',
    'www.bgsu.edu',
    'www.desu.edu',
    'www.newpaltz.edu',
    'www.cmich.edu',
    'www.usm.edu',
    'www.iusb.edu',
    'www.stmarytx.edu',
    'www.ship.edu',
    'www.etsu.edu',
    'www.panam.edu',
    'www.jsums.edu',
    'www.ocu.edu',
    'www.frostburg.edu',
    'www.lasalle.edu',
    'www.alfred.edu',
    'www.monmouth.edu',
    'www.snhu.edu',
    'www.roosevelt.edu',
    'www.drake.edu',
    'www.ship.edu',
    'www.duq.edu',
    'www.gcsu.edu',
    'www.georgiasouthern.edu',
    'www.kennesaw.edu',
    'www.liu.edu',
    'www.luc.edu',
    'www.nku.edu',
    'www.ltu.edu',
    'www.cau.edu',
    'www.csun.edu',
    'www.cua.edu',
    'www.ohiodominican.edu',
    'www.ferris.edu',
    'www.fitchburgstate.edu',
    'www.hpu.edu',
    'www.northwood.edu',
    'www.jwu.edu',
    'www.govst.edu',
    'www.troy.edu',
    'www.stevens.edu',
    'www.fau.edu',
    'www.ggu.edu',
    'www.howard.edu',
    'www.dom.edu',
]

let browser = ''

const fetchScreenshot = async (link) => {
    let filename = 'public/universities/'+link.split('.')[1]+'.png';
    
    if(fs.existsSync(__dirname+'/'+ filename)) {
        if(links.length > 0) {
            fetchScreenshot(links.pop());

            return;    
        }
    }

    let page = await browser.newPage();

    await page.setViewport({ width: 1366, height: 768});

    try {


        await page.goto('https://' + link, {
            waitUntil: 'networkidle2'
        });

        await page.evaluate(() => { document.querySelector('html').style.overflow = 'hidden'; })

        await page.screenshot({path: filename})

    } catch (err) {

        await page.goto('http://' + link, {
            waitUntil: 'networkidle2'
        });

        await page.evaluate(() => { document.querySelector('html').style.overflow = 'hidden'; })

        await page.screenshot({path: filename})

    } finally {
        await page.close();
        if(links.length > 0) {
            fetchScreenshot(links.pop())        
        }
    }
 
}
const scrape = async () =>{
    browser = await puppet.launch({ headless: false, args: ['--hide-scrollbars','--start-maximized', '--no-sandbox', '--disable-setuid-sandbox'] });

    fetchScreenshot(links.pop()) 
}

scrape()