export default [
    {
        score: {
            min: 334,
            max: 340
        },
        universities: [
            { name: 'Massachusetts Institute of Technology', site: 'https://www.mit.edu' },
            { name: 'Stanford University', site: 'https://www.stanford.edu' },
            { name: 'University of California- Berkeley', site: 'https://www.berkeley.edu' },
            { name: 'University of Illinois – Urbana Champaign', site: 'https://www.uiuc.edu' },
            { name: 'University of Michigan Ann Arbor', site: 'https://www.umich.edu' },
            { name: 'Cornell University', site: 'https://www.cornell.edu' },
            { name: 'University of Texas at Austin', site: 'https://www.utexas.edu' },
            { name: 'University of Maryland – College park', site: 'https://www.umd.edu' },
            { name: 'University of California – San Diego', site: 'https://www.ucsd.edu' },
            { name: 'California Institute of Technology', site: 'https://www.caltech.edu' },
            { name: 'University of Wisconsin- Madison', site: 'https://www.wisc.edu' },
            { name: 'University of California Los Angles', site: 'https://www.ucla.edu' },
            { name: 'Harvard University', site: 'https://www.harvard.edu' },
            { name: 'Carnegie Mellon University', site: 'https://www.cmu.edu' },
        ]
    },
    {
        score: {
            min: 325,
            max: 333
        },
        universities: [
            { name: 'Purdue University –West Lafayette', site: 'https://www.purdue.edu' },
            { name: 'Princeton University', site: 'https://www.princeton.edu' },
            { name: 'Pennsylvania State University –Univ Park', site: 'https://www.psu.edu' },
            { name: 'Georgia Institute of Technology', site: 'https://www.gatech.edu' },
            { name: 'Virginia poly Tech', site: 'https://www.vt.edu' },
            { name: 'Texas A & M College Station', site: 'https://www.tamu.edu' },
            { name: 'Duke University', site: 'https://www.duke.edu' },
            { name: 'University of Washington – Seattle', site: 'https://www.washington.edu' },
            { name: 'University of Minnesota', site: 'https://www.umn.edu' },
            { name: 'Columbia University', site: 'https://www.columbia.edu' },
            { name: 'Yale University', site: 'https://www.yale.edu' },
            { name: 'Ohio State University', site: 'https://www.osu.edu' },
            { name: 'University of Pittsburgh', site: 'https://www.pitt.edu' },
            { name: 'Brown university (RI)', site: 'https://www.brown.edu' },
            { name: 'John Hopkins University', site: 'https://www.jhu.edu' },
            { name: 'North Carolina State University', site: 'https://www.ncsu.edu' },
            { name: 'Dartmouth College, NH', site: 'https://www.dartmouth.edu' },
            { name: 'Iowa State University', site: 'https://www.iastate.edu' },
            { name: 'University of California- Santa Barbara', site: 'https://www.ucsb.edu' },
            { name: 'Case Western Reserve University', site: 'https://www.cwru.edu' },
            { name: 'Northwestern University (IL)', site: 'https://www.northwestern.edu' },
            { name: 'Arizona State University', site: 'https://www.asu.edu' },
            { name: 'University of Iowa', site: 'https://www.uiowa.edu' },
            { name: 'Rutgers, State Univ of NJ, New Brunswick', site: 'https://www.rutgers.edu' },
            { name: 'Rice University', site: 'https://www.rice.edu' },
            { name: 'University of Rochester', site: 'https://www.rochester.edu' },
            { name: 'University of Virginia', site: 'https://www.virginia.edu' },
            { name: 'University of Pennsylvania', site: 'https://www.upenn.edu' },
        ]
    },
    {
        score: {
            min: 321,
            max: 325
        },
        universities: [
            { name: 'University of Delaware', site: 'https://www.udel.edu' },
            { name: 'University of California – Davis', site: 'https://www.ucdavis.edu' },
            { name: 'University of Colorado –Boulder', site: 'https://www.colorado.edu' },
            { name: 'University of Notre Dame', site: 'https://www.nd.edu' },
            { name: 'University of Chicago', site: 'https://www.uchicago.edu' },
            { name: 'Lehigh University (PA)', site: 'https://www.lehigh.edu' },
            { name: 'University of Southern California', site: 'https://www.usc.edu' },
            { name: 'Rensselaer Polytechnic Institute (NY)', site: 'https://www.rpi.edu' },
            { name: 'University of Cincinnati', site: 'https://www.uc.edu' },
            { name: 'University of Florida; Gainesville', site: 'https://www.ufl.edu' },
            { name: 'Washington University St Louis', site: 'https://www.wustl.edu' },
            { name: 'Vanderbilt University (TN)', site: 'https://www.vanderbilt.edu' },
            { name: 'University of California - Irvine', site: 'https://www.uci.edu' },
            { name: 'Michigan State University', site: 'https://www.msu.edu' },
            { name: 'University of Massachusetts – Amherst', site: 'https://www.umass.edu' },
            { name: 'Kansas State University', site: 'https://www.ksu.edu' },
            { name: 'University of Alabama- Tuscaloosa', site: 'https://www.ua.edu' },
            { name: 'University of Arizona-Tucson', site: 'https://www.arizona.edu' },
            { name: 'University of North Carolina- Chapel Hill', site: 'https://www.unc.edu' },
            { name: 'Colorado School of Mines', site: 'https://www.mines.edu' },
            { name: 'University of Illinois at Chicago', site: 'https://www.uic.edu' },
            { name: 'University of New Hampshire', site: 'https://www.unh.edu' },
            { name: 'University of New Mexico', site: 'https://www.unm.edu' },
            { name: 'Boston University', site: 'https://www.bu.edu' },
            { name: 'Colorado State University', site: 'https://www.colostate.edu' },
            { name: 'Auburn University', site: 'https://www.auburn.edu' },
            { name: 'University of Buffalo', site: 'https://www.buffalo.edu' },
            { name: 'University of Akron', site: 'https://www.uakron.edu' },
            { name: 'Drexel University', site: 'https://www.drexel.edu' },
            { name: 'Syracuse University', site: 'https://www.syr.edu' },
            { name: 'Oregon State University', site: 'https://www.oregonstate.edu' },
            { name: 'Clemson University', site: 'https://www.clemson.edu' },
        ]
    },
    {
        score: {
            min: 315,
            max: 320
        },
        universities: [
            { name: 'University of Missouri – Rolla', site: 'https://www.missouri.edu' },
            { name: 'University of Nebraska Lincoln', site: 'https://www.unl.edu' },
            { name: 'University of Connecticut', site: 'https://www.uconn.edu' },
            { name: 'University of Utah', site: 'https://www.utah.edu' },
            { name: 'University of Tennessee-Knoxville', site: 'https://www.utk.edu' },
            { name: 'West Virginia University', site: 'https://www.wvu.edu' },
            { name: 'University of Kansas', site: 'https://www.ku.edu' },
            { name: 'SUNY- stony brook', site: 'https://www.stonybrook.edu/' },
            { name: 'University of Georgia', site: 'https://www.uga.edu' },
            { name: 'University of Missouri-Columbia', site: 'https://www.mizzou.edu' },
            { name: 'Oklahoma State University', site: 'https://www.okstate.edu' },
            { name: 'Louisiana State University-Baton Rouge', site: 'https://www.louisiana.edu/' },
            { name: 'University of South Carolina', site: 'https://www.sc.edu' },
            { name: 'Tulane University', site: 'https://www.tulane.edu' },
            { name: 'Indiana University - Bloomington', site: 'https://www.indiana.edu' },
            { name: 'University of Oklahoma', site: 'https://www.ou.edu' },
            { name: 'University of Miami', site: 'https://www.miami.edu' },
            { name: 'University of Texas – Dallas', site: 'https://www.utdallas.edu' },
            { name: 'Ohio University –Athens', site: 'https://www.ohio.edu' },
            { name: 'University of Houston –Houston', site: 'https://www.uh.edu' },
            { name: 'Michigan technological University', site: 'https://www.mtu.edu' },
            { name: 'University of Maine', site: 'https://www.umaine.edu' },
            { name: 'University of Kentucky', site: 'https://www.uky.edu' },
            { name: 'George Washington University', site: 'https://www.gwu.edu' },
            { name: 'University of Central Florida', site: 'https://www.ucf.edu' },
        ]
    },
    {
        score: {
            min: 309,
            max: 314
        },
        universities: [
            { name: 'Northern Illinois University', site: 'https://www.niu.edu' },
            { name: 'Indiana University Purdue University', site: 'https://www.iupui.edu' },
            { name: 'University of Memphis', site: 'https://www.memphis.edu' },
            { name: 'University of Nevada Los Vegas', site: 'https://www.unlv.edu' },
            { name: 'University of Alabama-Huntsville', site: 'https://www.uah.edu' },
            { name: 'University of Idaho', site: 'https://www.uidaho.edu' },
            { name: 'Mississippi State university', site: 'https://www.msstate.edu' },
            { name: 'University of Missouri, Kansas City', site: 'https://www.umkc.edu' },
            { name: 'University of North Carolina-Charlotte', site: 'https://www.uncc.edu' },
            { name: 'Oregon Graduate Institute of Science &Tech', site: 'https://www.ogi.edu' },
            { name: 'George Mason University', site: 'https://www.gmu.edu' },
            { name: 'University of Indianapolis', site: 'https://www.uindy.edu' },
            { name: 'University of Nebraska Omaha', site: 'https://www.unomaha.edu' },
            { name: 'University of South Florida- Tampa', site: 'https://www.usf.edu' },
            { name: 'Middle Tennessee State University', site: 'https://www.mtsu.edu' },
            { name: 'Polytechnic University (NY)', site: 'https://www.poly.edu' },
            { name: 'University of New Orleans', site: 'https://www.uno.edu' },
            { name: 'University of Arkansas- Fayetteville', site: 'https://www.uark.edu' },
            { name: 'Tennessee Technological University', site: 'https://www.tntech.edu' },
            { name: 'University of South Florida', site: 'https://www.usf.edu' },
            { name: 'University of Louisiana-Lafayette', site: 'https://www.louisiana.edu' },
            { name: 'Florida Institute of Technology', site: 'https://www.fit.edu' },
            { name: 'Illinois Institute of Technology', site: 'https://www.iit.edu' },
            { name: 'Washington State University', site: 'https://www.wsu.edu' },
            { name: 'Georgia State University', site: 'https://www.gsu.edu' },
        ]
    },
    {
        score: {
            min: 301,
            max: 308
        },
        universities: [
            { name: 'Texas Tech University', site: 'https://www.ttu.edu' },
            { name: 'Wayne State University', site: 'https://www.wayne.edu' },
            { name: 'California State University, Sacramento', site: 'https://www.csus.edu' },
            { name: 'Missouri State University', site: 'https://www.missouristate.edu' },
            { name: 'New Mexico State University', site: 'https://www.nmsu.edu' },
            { name: 'North Dakota State University', site: 'https://www.ndsu.edu' },
            { name: 'University of Texas-Arlington', site: 'https://www.uta.edu' },
            { name: 'Clarkson University', site: 'https://www.clarkson.edu' },
            { name: 'Wright State University', site: 'https://www.wright.edu' },
            { name: 'University of Tennessee Chattanooga', site: 'https://www.utc.edu' },
            { name: 'University of Tulsa', site: 'https://www.utulsa.edu' },
            { name: 'Portland state university', site: 'https://www.pdx.edu' },
            { name: 'University of Vermont', site: 'https://www.uvm.edu' },
            { name: 'Baylor University, Texas', site: 'https://www.baylor.edu' },
            { name: 'Villanova University', site: 'https://www.villanova.edu' },
            { name: 'University of Tampa', site: 'https://www.ut.edu' },
            { name: 'Louisiana Tech. University', site: 'https://www.latech.edu' },
            { name: 'New Jersey Institute of Technology', site: 'https://www.njit.edu' },
            { name: 'Idaho State University', site: 'https://www.isu.edu' },
            { name: 'Wichita State University', site: 'https://www.wichita.edu' },
            { name: 'University of Mississippi', site: 'https://www.olemiss.edu' },
            { name: 'Northeastern University', site: 'https://www.northeastern.edu' },
            { name: 'Southern Illinois University-Edwardsville', site: 'https://www.siue.edu' },
            { name: 'University of Alaska- Fairbanks', site: 'https://www.uaf.edu' },
            { name: 'Pace University, NY', site: 'https://www.pace.edu' },
            { name: 'Wright State University', site: 'https://www.wright.edu' },
            { name: 'Chicago State University', site: 'https://www.csu.edu' },
            { name: 'South Dakota State University', site: 'https://www.sdsu.edu' },
            { name: 'East Carolina University', site: 'https://www.ecu.edu' },
            { name: 'University of North Texas', site: 'https://www.unt.edu' },
            { name: 'SUNY Institute of Technology', site: 'https://www.sunyit.edu' },
            { name: 'University of Missouri at St Louis', site: 'https://www.umsl.edu' },
            { name: 'University of Northern Iowa', site: 'https://www.uni.edu' },
            { name: 'University of Toledo', site: 'https://www.utoledo.edu' },
            { name: 'University of Illinois at Springfield', site: 'https://www.uis.edu' },
            { name: 'Old Dominion University, Virginia', site: 'https://www.odu.edu' },
        ]
    },
    {
        score: {
            min: 291,
            max: 300
        },
        universities: [
            { name: 'Northwest Missouri State University', site: 'https://www.nwmissouri.edu' },
            { name: 'Lamar University', site: 'https://www.lamar.edu' },
            { name: 'Illinois State University, Normal', site: 'https://www.ilstu.edu' },
            { name: 'University of Louisville', site: 'https://www.louisville.edu' },
            { name: 'Texas A & M University, Commerce', site: 'https://new.tamuc.edu/' },
            { name: 'Colorado Technical University, Colorado Springs', site: 'https://www.coloradotech.edu' },
            { name: 'Boise State university, Idaho', site: 'https://www.boisestate.edu' },
            { name: 'Montana State University, Bozeman', site: 'https://www.montana.edu' },
            { name: 'South Dakota School of Mines & technology', site: 'https://www.sdsmt.edu' },
            { name: 'North Carolina Agricultural & Tech State University', site: 'https://www.ncat.edu' },
            { name: 'Southern Illinois University, Carbondale', site: 'https://www.siuc.edu' },
            { name: 'Florida International university', site: 'https://www.fiu.edu' },
            { name: 'North Dakota State University', site: 'https://www.und.edu' },
            { name: 'Western Kentucky University', site: 'https://www.wku.edu' },
            { name: 'Bradley University', site: 'https://www.bradley.edu' },
            { name: 'Cleveland State University', site: 'https://www.csuohio.edu' },
            { name: 'University of Bridgeport –CT', site: 'https://www.bridgeport.edu' },
            { name: 'University of Dayton –Ohio', site: 'https://www.udayton.edu' },
            { name: 'Texas A & M university, Kingsville', site: 'https://www.tamuk.edu' },
            { name: 'University of West Florida, Pensacola', site: 'https://www.uwf.edu' },
            { name: 'Eastern Michigan University', site: 'https://www.emich.edu' },
            { name: 'Minnesota State University, Mankato', site: 'https://www.mnsu.edu' },
            { name: 'Suffolk University, MA', site: 'https://www.suffolk.edu' },
            { name: 'University of North Carolina, Greensboro', site: 'https://www.uncg.edu' },
            { name: 'New Mexico Institute of Mining &Tech.', site: 'https://www.nmt.edu' },
            { name: 'University of Central Arkansas', site: 'https://www.uca.edu' },
            { name: 'Southeastern University, DC', site: 'https://www.seu.edu' },
            { name: 'University of Hawaii', site: 'https://www.hawaii.edu' },
            { name: 'University of Texas, Tyler', site: 'https://www.uttyler.edu' },
            { name: 'Eastern Washington University', site: 'https://www.ewu.edu' },
            { name: 'Southern Oregon University, Ashland', site: 'https://www.sou.edu' },
            { name: 'University of Texas at San Antonio', site: 'https://www.utsa.edu' },
            { name: 'State University of West Georgia', site: 'https://www.westga.edu' },
            { name: 'Ball State University', site: 'https://www.bsu.edu' },
            { name: 'University of Texas El Paso', site: 'https://www.utep.edu' },
            { name: 'Columbus State University', site: 'https://www.columbusstate.edu/' },
            { name: 'Arkansas State University', site: 'https://www.astate.edu' },
            { name: 'University of Denver', site: 'https://www.du.edu' },
            { name: 'North Dakota State University', site: 'https://www.ndsu.edu' },
            { name: 'New York Institute of Technology', site: 'https://www.nyit.edu' },
            { name: 'California State University, Chico', site: 'https://www.csuchico.edu' },
            { name: 'Dakota State University', site: 'https://www.dsu.edu' },
            { name: 'St Cloud State University', site: 'https://www.stcloudstate.edu' },
            { name: 'Marquette University', site: 'https://www.marquette.edu' },
        ]
    },
    {
        score: {
            min: 260,
            max: 290
        },
        universities: [
            { name: 'Temple University, PA', site: 'https://www.temple.edu' },
            { name: 'City College of the City of New York', site: 'https://www.cuny.edu' },
            { name: 'Northeastern Illinois University', site: 'https://www.neiu.edu' },
            { name: 'University of Detroit Mercy', site: 'https://www.udmercy.edu' },
            { name: 'University of Arkansas Little Rock', site: 'https://www.ualr.edu' },
            { name: 'California State University, Fresno', site: 'https://www.csufresno.edu' },
            { name: 'Alabama A & M University', site: 'https://www.aamu.edu' },
            { name: 'Widener University, Pennsylvania', site: 'https://www.widener.edu' },
            { name: 'Alcorn State University', site: 'https://www.alcorn.edu' },
            { name: 'Gannon University', site: 'https://www.gannon.edu' },
            { name: 'University of Findlay-Ohio', site: 'https://www.findlay.edu' },
            { name: 'San Diego State University, California', site: 'https://www.sdsu.edu' },
            { name: 'Ball State University', site: 'https://www.bsu.edu' },
            { name: 'Northwestern Polytechnic University', site: 'https://www.npu.edu' },
            { name: 'Jacksonville State University', site: 'https://www.jsu.edu' },
            { name: 'Saint Joseph University', site: 'https://www.sju.edu' },
            { name: 'Chapman University', site: 'https://www.chapman.edu' },
            { name: 'Kent State University', site: 'https://www.kent.edu' },
            { name: 'Ferris State University', site: 'https://www.ferris.edu' },
            { name: 'University of New Haven, CT', site: 'https://www.newhaven.edu' },
            { name: 'Farleigh Dickinson University, New Jersey', site: 'https://www.fdu.edu' },
            { name: 'State University of New York, Albany', site: 'https://www.albany.edu' },
            { name: 'College of William & Mary', site: 'https://www.wm.edu' },
            { name: 'East Tennessee State University', site: 'https://www.etsu.edu' },
            { name: 'Southwest Texas State University, San Marcos', site: 'https://www.txstate.edu' },
            { name: 'DePaul University', site: 'https://www.depaul.edu' },
            { name: 'Mc Neese State University', site: 'https://www.mcneese.edu' },
            { name: 'Oakland University', site: 'https://www.oakland.edu' },
            { name: 'Sam Houston State University', site: 'https://www.shsu.edu' },
            { name: 'San Jose state University', site: 'https://www.sjsu.edu' },
            { name: 'William Patterson University', site: 'https://www.wpunj.edu' },
            { name: 'Western Carolina University', site: 'https://www.wcu.edu' },
            { name: 'University of Central Oklahoma', site: 'https://www.uco.edu/' },
            { name: 'Widener University', site: 'https://www.widener.edu' },
            { name: 'University of St Thomas, MN', site: 'https://www.stthomas.edu' },
            { name: 'Western Illinois university', site: 'https://www.wiu.edu' },
            { name: 'Bowling Green State University, Ohio', site: 'https://www.bgsu.edu' },
            { name: 'Delaware State University', site: 'https://www.desu.edu' },
            { name: 'State University of New York, New Paltz', site: 'https://www.newpaltz.edu' },
            { name: 'Central Michigan University', site: 'https://www.cmich.edu' },
            { name: 'University of Southern Mississippi', site: 'https://www.usm.edu' },
            { name: 'Indian University South Bend', site: 'https://www.iusb.edu' },
            { name: 'Saint Mary’s University San Antonio', site: 'https://www.stmarytx.edu' },
            { name: 'Shippensburg University, PA', site: 'https://www.ship.edu' },
            { name: 'East Tennessee State University', site: 'https://www.etsu.edu' },
            { name: 'University of Texas, Pan America', site: 'https://www.utrgv.edu' },
            { name: 'Jackson State University', site: 'https://www.jsums.edu' },
            { name: 'Oklahoma City University', site: 'https://www.ocu.edu' },
            { name: 'Frostburg State University', site: 'https://www.frostburg.edu' },
            { name: 'La Salle University, PA', site: 'https://www.lasalle.edu' },
            { name: 'Alfred University', site: 'https://www.alfred.edu' },
            { name: 'Monmouth University-New Jersey', site: 'https://www.monmouth.edu' },
            { name: 'Southern New Hampshire University', site: 'https://www.snhu.edu' },
            { name: 'Roosevelt University Chicago', site: 'https://www.roosevelt.edu' },
            { name: 'Drake university', site: 'https://www.drake.edu' },
            { name: 'Shippensburg University of Pennsylvania', site: 'https://www.ship.edu' },
            { name: 'Duquesne University', site: 'https://www.duq.edu' },
            { name: 'Georgia College & State University', site: 'https://www.gcsu.edu' },
            { name: 'Georgia Southern University', site: 'https://www.georgiasouthern.edu' },
            { name: 'Kennesaw State University', site: 'https://www.kennesaw.edu' },
            { name: 'Long Island University', site: 'https://www.liu.edu' },
            { name: 'Loyola University Chicago', site: 'https://www.luc.edu' },
            { name: 'Northern Kentucky University', site: 'https://www.nku.edu' },
            { name: 'Lawrence Tech University', site: 'https://www.ltu.edu' },
            { name: 'Clark Atlanta University', site: 'https://www.cau.edu' },
            { name: 'California State University, Northridge', site: 'https://www.csun.edu' },
            { name: 'Catholic University of America, Washington', site: 'https://www.cua.edu' },
            { name: 'Ohio Dominican College (University), Ohio', site: 'https://www.ohiodominican.edu' },
            { name: 'Ferris State University, Michigan', site: 'https://www.ferris.edu' },
            { name: 'Fitchburg State University, MA', site: 'https://www.fitchburgstate.edu' },
            { name: 'Hawaii Pacific University, Hawaii', site: 'https://www.hpu.edu' },
            { name: 'Northwood University, Michigan', site: 'https://www.northwood.edu' },
            { name: 'Johnson and Wales University, RI', site: 'https://www.jwu.edu' },
            { name: 'Governors State University, Parkway IL', site: 'https://www.govst.edu' },
            { name: 'Troy State University, Alabama', site: 'https://www.troy.edu' },
            { name: 'Stevens Institute of Technology', site: 'https://www.stevens.edu' },
            { name: 'Florida Atlantic University, Boca Raton', site: 'https://www.fau.edu' },
            { name: 'Golden Gate University', site: 'https://www.ggu.edu' },
            { name: 'Howard University', site: 'https://www.howard.edu' },
            { name: 'Dominican University', site: 'https://www.dom.edu' },
        ]
    }
]